name: Build and Push Image to GAR and Deploy to Cloud Run

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Pull previous image for cache
        run: |
          docker pull us-central1-docker.pkg.dev/iksana-opticals-llp/nextjs-demo/nextjs || exit 0

      - name: Build image
        run: docker build . --tag us-central1-docker.pkg.dev/iksana-opticals-llp/nextjs-demo/nextjs --cache-from us-central1-docker.pkg.dev/iksana-opticals-llp/nextjs-demo/nextjs

      - name: Push image
        run: docker push us-central1-docker.pkg.dev/iksana-opticals-llp/nextjs-demo/nextjs

      - name: Deploy to Cloud Run
        run: gcloud run deploy nextjs --image us-central1-docker.pkg.dev/iksana-opticals-llp/nextjs-demo/nextjs --region us-central1 --platform managed --allow-unauthenticated
